<?php
session_start();
require_once 'config/db.php';

if (!isset($_SESSION['student_id'])) { exit("Access Denied"); }

$sid = $_SESSION['student_id'];
$stmt = $pdo->prepare("SELECT * FROM students WHERE student_id = ?");
$stmt->execute([$sid]);
$student = $stmt->fetch();
?>

<!DOCTYPE html>
<html>
<head>
    <title>Official Grade Slip - BCC Inc.</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #0047AB; padding-bottom: 20px; margin-bottom: 30px; }
        .info-table { width: 100%; margin-bottom: 30px; }
        .grade-table { width: 100%; border-collapse: collapse; }
        .grade-table th, .grade-table td { border: 1px solid #ccc; padding: 12px; text-align: left; }
        .grade-table th { background-color: #f2f2f2; }
        .footer { margin-top: 50px; display: flex; justify-content: space-between; }
        .signature { border-top: 1px solid #333; width: 200px; text-align: center; padding-top: 5px; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body>

    <div class="header">
        <h1 style="margin: 0; color: #0047AB;">Binalbagan Catholic College Inc.</h1>
        <p>Enlow St., Binalbagan, Negros Occidental</p>
        <h2>OFFICIAL GRADE SLIP</h2>
    </div>

    <table class="info-table">
        <tr>
            <td><strong>Student Name:</strong> <?php echo $student['first_name'] . ' ' . $student['last_name']; ?></td>
            <td><strong>Student ID:</strong> <?php echo $student['student_id']; ?></td>
        </tr>
        <tr>
            <td><strong>Program:</strong> <?php echo $student['program']; ?></td>
            <td><strong>Date Issued:</strong> <?php echo date('M d, Y'); ?></td>
        </tr>
    </table>

    <table class="grade-table">
        <thead>
            <tr>
                <th>Subject Code</th>
                <th>Description</th>
                <th>Final Grade</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
    <?php
    $stmt = $pdo->prepare("
        SELECT sub.subject_code, sub.subject_name, g.final_rating 
        FROM subjects sub
        LEFT JOIN grades g ON sub.id = g.subject_id AND g.student_id = ?
        WHERE sub.program = ?
    ");
    
    // THE FIX: Pull the ID and Program directly from the logged-in student's session!
    $stmt->execute([$_SESSION['student_id'], $_SESSION['program']]);

    if ($stmt->rowCount() > 0) {
        while ($row = $stmt->fetch()) {
            $final = !empty($row['final_rating']) ? $row['final_rating'] : "TBA";
            
            // Automatically calculate Pass/Fail Remarks
            $remarks = "—";
            if ($final != "TBA") {
                // Assuming grades 1.0 to 3.0 are passing
                $remarks = ($final <= 3.0) ? "<span style='color: green; font-weight: bold;'>PASSED</span>" : "<span style='color: red; font-weight: bold;'>FAILED</span>";
            }
            
            echo "<tr style='border-bottom: 1px solid #ccc;'>
                    <td style='padding: 12px;'>{$row['subject_code']}</td>
                    <td style='padding: 12px;'>{$row['subject_name']}</td>
                    <td style='padding: 12px; text-align: center; font-weight: bold;'>{$final}</td>
                    <td style='padding: 12px; text-align: center;'>{$remarks}</td>
                  </tr>";
        }
    } else {
        echo "<tr><td colspan='4' style='padding: 20px; text-align: center;'>No subjects enrolled.</td></tr>";
    }
    ?>
</tbody>
    </table>

    <div class="footer">
        <div>
            <p>Generated by: <strong>BCC Student Portal</strong></p>
        </div>
        <div class="signature">
            <strong>Office of the Registrar</strong>
        </div>
    </div>

    <div class="no-print" style="margin-top: 40px; text-align: center;">
        <button onclick="window.print()" style="padding: 15px 30px; background: #0047AB; color: white; border: none; cursor: pointer; border-radius: 5px; font-weight: bold;">
            <i class="fas fa-print"></i> Print Grade Slip
        </button>
    </div>

</body>
</html>