<?php
session_start();
require_once 'config/db.php';

if (!isset($_SESSION['student_id'])) { exit("Access Denied"); }

$sid = $_SESSION['student_id'];
$stmt = $pdo->prepare("SELECT * FROM students WHERE student_id = ?");
$stmt->execute([$sid]);
$student = $stmt->fetch();
?>

<!DOCTYPE html>
<html>
<head>
    <title>Official Class Schedule - BCC Inc.</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #0047AB; padding-bottom: 20px; margin-bottom: 30px; }
        .info-table { width: 100%; margin-bottom: 30px; }
        .schedule-table { width: 100%; border-collapse: collapse; }
        .schedule-table th, .schedule-table td { border: 1px solid #ccc; padding: 12px; text-align: left; }
        .schedule-table th { background-color: #f2f2f2; }
        .footer { margin-top: 50px; display: flex; justify-content: space-between; }
        .signature { border-top: 1px solid #333; width: 200px; text-align: center; padding-top: 5px; }
        @media print { 
            .no-print { display: none; } 
            body { padding: 0; }
        }
    </style>
</head>
<body>

    <div class="header">
        <h1 style="margin: 0; color: #0047AB;">Binalbagan Catholic College Inc.</h1>
        <p>Enlow St., Binalbagan, Negros Occidental</p>
        <h2>OFFICIAL CLASS SCHEDULE</h2>
    </div>

    <table class="info-table">
        <tr>
            <td><strong>Student Name:</strong> <?php echo $student['first_name'] . ' ' . $student['last_name']; ?></td>
            <td><strong>Student ID:</strong> <?php echo $student['student_id']; ?></td>
        </tr>
        <tr>
            <td><strong>Program:</strong> <?php echo $student['program']; ?></td>
            <td><strong>Date Issued:</strong> <?php echo date('M d, Y'); ?></td>
        </tr>
    </table>

    <table class="schedule-table">
        <thead>
            <tr>
                <th>Course Code</th>
                <th>Description</th>
                <th>Days & Time</th>
                <th>Room</th>
                <th>Instructor</th>
            </tr>
        </thead>
        <tbody>
        <?php
        $stmt = $pdo->prepare("SELECT subject_code, subject_name, days_time, room, instructor FROM subjects WHERE program = ?");
        $stmt->execute([$student['program']]);

        if ($stmt->rowCount() > 0) {
            while ($row = $stmt->fetch()) {
                $days = !empty($row['days_time']) ? $row['days_time'] : "TBA";
                $room = !empty($row['room']) ? $row['room'] : "TBA";
                $instructor = !empty($row['instructor']) ? $row['instructor'] : "TBA";

                echo "<tr>
                        <td>{$row['subject_code']}</td>
                        <td>{$row['subject_name']}</td>
                        <td>{$days}</td>
                        <td>{$room}</td>
                        <td>{$instructor}</td>
                      </tr>";
            }
        } else {
            echo "<tr><td colspan='5' style='padding: 20px; text-align: center;'>No schedule available.</td></tr>";
        }
        ?>
        </tbody>
    </table>

    <div class="footer">
        <div>
            <p>Generated by: <strong>BCC Student Portal</strong></p>
        </div>
        <div class="signature">
            <strong>Office of the Registrar</strong>
        </div>
    </div>

    <div class="no-print" style="margin-top: 40px; text-align: center;">
        <button onclick="window.print()" style="padding: 15px 30px; background: #0047AB; color: white; border: none; cursor: pointer; border-radius: 5px; font-weight: bold; font-size: 16px;">
            Print Schedule
        </button>
        <br><br>
        <a href="student-dashboard.php" style="color: #0047AB; text-decoration: none; font-weight: bold;">&larr; Back to Dashboard</a>
    </div>

</body>
</html>